### ISSUE TITLE
Unable to compile with phoenix_html 4.0.0

### ISSUE THREAD

**Issue by thomasdziedzic-calmwave** [LivewareProblems/Orion#16]
When I tried to test out orion in my project, I get the following error:

```
==> orion
Compiling 12 files (.ex)

== Compilation error in file lib/orion_web/layout_view.ex ==
** (RuntimeError) use Phoenix.HTML is no longer supported in v4.0.

To keep compatibility with previous versions, add {:phoenix_html_helpers, "~> 1.0"} to your mix.exs deps
and then, instead of "use Phoenix.HTML", you might:

    import Phoenix.HTML
    import Phoenix.HTML.Form
    use PhoenixHTMLHelpers


    (phoenix_html 4.0.0) expanding macro: Phoenix.HTML.__using__/1
    lib/orion_web/layout_view.ex:3: OrionWeb.LayoutView (module)
    ...
```

This is coming from this line in orion: https://github.com/LivewareProblems/Orion/blob/dfe10222a4f5b8a866f3e883293f6d0a27e013d0/lib/orion_web.ex#L35C1-L35C23

Which is coming from this line in phoenix_html: https://github.com/phoenixframework/phoenix_html/blob/c50f33d20f98f6fa2a07f42fc00b3ce8c6c341ba/lib/phoenix_html.ex#L78

I found that there might be a branch that tries to fix this issue: https://github.com/LivewareProblems/Orion/compare/main...slower-than-y#diff-a6f7bdf0bf38ece9e42adc0df1ed964de91fc00b0653ceba344d7998afd51272R35-R37

**Comment by DianaOlympos** [comment]
I will have a look tomorrow, but yeah make sense

**Comment by DianaOlympos** [comment]
Should be fixed with 1.0.5

Thank you so much
❤️ 💙 💜 💚 💛 🧡 🤍 🖤 🤎 💖

**Comment by thomasdziedzic-calmwave** [comment]
Thanks, I just tried it and it works!
